require File.join(File.dirname(__FILE__), '..', '..', 'lib', 'coo-coo', 'platform')

NVCC=ENV.fetch("NVCC", "nvcc")
# FIXME if windows/linux; windows doesn't like Wall
if CooCoo::Platform.windows?
  #NVCCFLAGS="--cl-version=2015"
  NVCCFLAGS=""
else
  NVCCFLAGS="--compiler-options='-fPIC -Wall'"
end

DLEXT=RbConfig::CONFIG['DLEXT']

task :default => "buffer.#{DLEXT}"

task :clean do
  sh("rm -f buffer.#{DLEXT} buffer.ext buffer.lib")
end

file "buffer.#{DLEXT}" => 'buffer.cu' do |t|
	sh("#{NVCC} #{NVCCFLAGS} -shared -o #{t.name} #{t.sources.join(' ')}")
end

